marklogic-community/RunDMC

- data/admin/index.xml
- src/admin/controller/edit-by-uri.xqy
- src/admin/css/admin.css
- src/admin/js/functions.js
Add a quick entry box to the index.xml to immediately jump to the edit
screen for a particular URI.  Display an alert if the URI does not
exist.
> #375 Add ability to edit by URI

- src/stackunderflow/stackoverflow.css
- src/stackunderflow/stackunderflow-1.0.3.js
- src/view/tag-library.xsl
Update to support the latest StackExchange API - 2.2.  Tweak CSS/HTML to handle the current JSON returned by the 2.2 API.  Remove key from the repo.
> Issue #354 - Fix StackUnderflow to work with 2.2 API

- data/index.xml
- src/admin/controller/modules/admin-ops.xqy
- src/admin/model/form2xml.xsl
- src/controller/access.xml
- src/controller/recent.xqy
- src/controller/rewrite.xqm
- src/css/screen.css
- src/js/functions.js
Changes include:
- Display of recent changes (index.xml; functions.js, screen.css)
- Retrieval of recently changed content (access.xml, rewrite.xqm, rewriter.xqy)
- Changed XSLT that handles updating content so that the last-updated field gets set to *now* unless specified in the form
> Recentupdates

- src/model/data-access.xqy
> #489 Make $doc-element-names variable public

- src/apidoc/config/template.xhtml
- src/css/screen.css
Complementary docapp branch PR for PR #502.  
Fix the CSS on the drop-down below the button with the user's name.  Background is now black (not transparent), matching the login box drop-down.  Also, text is solid white without shadow, also matching the login box color.
Also, change the styling to use bootstrap so the button has a consistent look and feel with developer.
> #473 docs site - Fix drop-down from button with user's name and change button style

- data/products/marklogic-server/8.0.xml
- src/css/screen.css
- src/view/tag-library.xsl
This can wait until after @dsokolsky's next docapp merge.
> Bootstrap icons

- rest-api/config/options/www.xml
- src/model/data-access.xqy
Dave,
www site was not showing blog content from dev site.  I corrected the collection name and also updated facet names.
Thanks!
Seong
> Fixed collection name for blog

- src/model/data-access.xqy
This is a minor edit.  I changed one of the facet value labels from "Pages" to "MarkLogic Overview".
Thanks!
> changed label for www facet value

- src/model/data-access.xqy
Hi Dave and Paxton,
Diane wanted ordering changed for facet values.  Very minor change...
Thanks!
> Changed facet item order

- src/admin/view/form.xsl
- src/controller/disqus-to-comments-pre-ML6.xsl
- src/controller/disqus-to-comments.xsl
- src/view/comments.xsl
- src/view/navigation.xsl
- src/view/page.xsl
- src/view/tag-library.xsl
- src/view/tutorial.xsl
- src/view/widgets.xsl
Got tired of random indentation. Made it consistent.
> whitespace changes only

- src/apidoc/js/toc_filter.js
- src/apidoc/view/page.xsl
making comments work on docs pages
> fixing #543

- src/admin/config/template.xhtml
- src/admin/controller/replace.xqy
- src/admin/css/admin.css
- src/admin/css/screen.css
- src/admin/js/functions.js
- src/admin/view/form.xsl
Switching to an AJAX request means we don't have to reload the page, which means changes to the editor layout aren't lost.
> #614 Changed content update to an AJAX request

- src/admin/js/functions.js
I wrote the buildAttr function because I didn't notice the existence of setAttribute(). Rewrote to use the simpler function.
> replaced buildAttr() with using setAttribute()

- data/admin/author.xml
- data/admin/blog.xml
- data/admin/blog/edit.xml
- data/admin/code.xml
- data/admin/index.xml
- data/admin/learn.xml
- data/admin/media.xml
- data/admin/ondemand.xml
- data/admin/pages.xml
- src/admin/config/template.xhtml
- src/admin/css/admin.css
- src/admin/css/screen.css
- src/admin/view/form.xsl
- src/admin/view/tag-library.xsl
Make the RunDMC Admin UI nicer to look at.
> DMC Admin UI refresh

- src/admin/config/template.xhtml
- src/admin/css/admin.css
- src/admin/js/functions.js
- src/admin/view/form.xsl
I replaced a bunch of XSL that was generating very specific JS code
with simpler JS functions.
> Eliminated a bunch of XSL in favor of JS

- src/lib/atom-lib.xqy
- src/test/atom-lib.xqy
Generate next and prev links correctly.
> #664 added unit tests and fixed some logic

- data/recipes.xml
- src/config/navigation.xml
- src/controller/recipe-search.xqy
- src/controller/rewrite.xqm
- src/css/screen.css
- src/js/recipes.js
Implemented /recipes page. 
I used Vue.js. The page is dynamic and allows for recipe-specific search. Almost all the content of the page is rendered by JS as a single Vue component. This is in part because because content pages have to be XML, which doesn't fly with things like `v-on:click`.
> Recipes page

- src/css/screen.css
- src/js/recipes.js
- make sure all types of search interaction actually trigger a search
- don't allow paging past the beginning or the end of results
- use proper mouse pointer on pagination control
- add pagination control after results
- report "no results" when appropriate
> several UI improvements to recipes page

- .gitignore
- data/recipes.xml
- src/config/template.xhtml
- src/controller/recipe-search.xqy
- src/js/recipes.js
Show tag facet on the Recipes page.
> Recipe facets

- data/index.xml
- src/css/custom-new.css
@dmcassel - Here are the hero changes for our meeting.  I am still waiting on approval from Rania and Christina.   
**Overview of the Issue:**
changing the home page hero to match the newer branding 
**Motivation for or Use Case**
choessive graphics between www and developer websites
**Environment**
Need to work with Dave C to QA changes cross platform
**Suggest a Fix**
I adjusted the image to point to the new hero. We were not able to just doa image swap becuase we are changing from svg to jpg.  
With this change I need to do some minor tweaking to the middle alignment of the text as the text was slightly heigher then it should have been, and to help with readability so the text lays on top of the darker parts of the image.
> Update homepage hero

- src/config/widgets.xml
- src/widgets/ebooks.xml
Removed Blogroll, as none of those blogs are active.
> Added widget to promote Multi-model book.

- src/lib/date-parser.xqy
- src/test/date-parser.xqy
Bingbot's "If-Modified-Since" field looks like "131445406060000000".
> Bingbot is using a differently-formatted date. Avoid an exception.

- rest-api/config/options/www.xml
- src/config/template.xhtml
- src/model/data-access.xqy
We are updating the WWW collections for the new MLC website as so much content has changed with the redesign, and it also tackles the much-needed purging of old content.
> Common nav

- src/config/template.xhtml
- src/css/apidoc-screen.css
- src/css/screen.css
- src/js/functions.js
- src/view/tag-library.xsl
#772 replace jQuery UI dialog with a Bootstrap one
> Fix curl download

- src/config/widgets.xml
- src/widgets/mlw-ad.xml
Addressing #775 , updated the MLW ad and swapped out the Security Roadshow ad for the MarkLogic World ad.  Tested the branch on staging, and it looked good.  @dmcassel looks good?  I'll merge in the morning if this looks safe.
> MLW18 ad placement

- data/people/recovery.xml
- data/people/reset.xml
- data/people/signup.xml
- src/js/profile.js
1. additional requirements for password validation
2. removal of mailing list options during signup
3. privacy notice on password recovery and signup page
> DMC + GDPR Compliance

- src/config/navigation.xml
- src/view/comments.xsl
2. Add notice on comments prior to widget.
> 1. Add a placeholder for apache nifi in navigation

- data/people/signup.xml
- src/controller/signup.xqy
1. remove phone
2. remove the list checkbox
3. change verbiage for opt in
4. update link for privacy
> Additional changes

- src/apidoc/config/10.0/document-list.xml
- src/apidoc/model/data-access.xqy
This merge fixes several bugs in Run-DMC.
> Merging the Docapp to fix some bugs.

- src/apidoc/config/10.0/document-list.xml
this has been removed from the docbuild
> remove mapreduce from 10.0 document-list. 
